### ISSUE TITLE
Colorblindness doesn't work

### ISSUE THREAD

**Issue by Belsima** [Repede/YawnWiderStation#105]
#### Brief description of the issue

When enabling monochromacy trait, you can see in full color (except HUD, which is now properly gray).

#### What you expected to happen

Everything onscreen to be gray.

#### What actually happened

It only effects the HUD.

#### Steps to reproduce
- Select custom species
- Go to VORE tab, select negative traits and select Monochromacy
- Join the game

![image](https://i.imgur.com/X9qxqlT.png)

**Comment by izac112** [comment]
You might want to forward this to the vorestation Github if its an issue with the colorblind system

**Comment by Belsima** [comment]
https://github.com/VOREStation/VOREStation/issues/3422

**Comment by Hawk-v3** [comment]
Appears to be fixed upstream according to the bugreport linked.
