### ISSUE TITLE
Signallers don't appear to work as they used to.

### ISSUE THREAD

**Issue by Hawk-v3** [Repede/YawnWiderStation#111]
Missing Functionality:
Cannot hack them to alter some inbuilt bits like stopping the beepbeep.
Can connect them to wires. Cannot pulse wires remotely.

Something changed recently?

#### Code Revision
Server revision:  - 2018-06-13
483a05c4f1031b33490464400750620e60bd4f73

**Comment by Hawk-v3** [comment]
Additional: Can't attach a circuit with the wire interface into a door.

**Comment by DeepIndigo** [comment]
I've been able to pulse wires remotely, but on occasion, a signaler will be a "dud" and fail to do it. Copying the signaler info to another signaler seems to avert this in some cases. Will test further as I'm able.

**Comment by Hawk-v3** [comment]
The more you can get, the more I can try and help. I've looked into it, but... I always seem to get duds.
