### ISSUE TITLE
Chaplain PDA listing

### ISSUE THREAD

**Issue by Cleftspear** [Repede/YawnWiderStation#124]
When a chaplain is on the station, multiple instances of his pda appear in the list

only one to show up

thirteen showed up 
![image](https://user-images.githubusercontent.com/40463749/41718937-16d4ac8a-7524-11e8-98f4-aed1a4849bb0.png)

#### Steps to reproduce
- Step 1 play as chaplain
- Step 2 look at pda

**Comment by Hawk-v3** [comment]
#137 Done and dusted.
