### ISSUE TITLE
Add TG's 'duplicate chat' handling.

### ISSUE THREAD

**Issue by Dwaggy** [Repede/YawnWiderStation#140]
no idea if it would be possible, but..fug it, would be awesome if so:

Adding in the way TG's code (i think it is) handles chat messages.

Currently, if we have a chat message that duplicates the one above, it just spams the chat box.

> X drops what they were holding, their right hand malfunctioning!
> X drops what they were holding, their right hand malfunctioning!
> X drops what they were holding, their right hand malfunctioning!

.. and so on.

If it's possible, idea would be to incorporate at some point the whole..

> X drops what they were holding, their right hand malfunctioning! **(x900)**

Its one of those features that..i'm..never sure why baycode/polaris/vore never adapted. maybe its something thats too deep in to the guts of the code and not actually possible without a rewrite of a huge amount of shit? IDK. but worth a thought of 'is it possible?', right? c:

**Comment by gozulio** [comment]
i know someone trying to port goon code for a similar reason i think, but its like, over 1000 lines of code to go through just for the to_chat() proc
