### ISSUE TITLE
Make chaplain hear ghosts (sometimes)

### ISSUE THREAD

**Issue by Repede** [Repede/YawnWiderStation#142]
I remember the chaplain used to be able to hear nearby ghosts, rarely. Only like, one message out of 50 would go through, it was on TG I think. It was a fun thing for chaplains to do since it would let them ICly find where a corpse people are looking for could be.

It would be neat to have something like that, maybe add mechanics to make the chance of hearing ghosts higher or lower depending on circumstances (Held item? Being in the chapel? Being in the confession boot? Praying?)

**Comment by Hawk-v3** [comment]
This shouldn't be TOO hard to do, should it? I'm assuming it'd be in wherever the list of who hears deadchat goes.

We could use the "You almost hear" text from unconsciousness too.

**Comment by Repede** [comment]
I've never peeked at how deadsay and stuff works myself. But it probably shouldn't be hard. But at the same time, this is super low priority as a enhancement hah.
