### ISSUE TITLE
RUST control consoles sometimes randomly lock up.

### ISSUE THREAD

**Issue by Hawk-v3** [Repede/YawnWiderStation#145]
See Title. Console sometimes just... Stop working.

Anyone with any info on how or why or when would be appreciated.

**Comment by Repede** [comment]
Is it possible it's caused by a EMP?

**Comment by gozulio** [comment]
This only happens when the reactors field has failed.
It could be an EMP, but i don't think the R-UST has EMP procs, or emag procs.

**Comment by gozulio** [comment]
https://github.com/Repede/YawnWiderStation/blob/e797345dcb93340a796e062eb1187d1e3b815fa3/code/game/machinery/computer/computer.dm#L89-L91
emp_act calls this proc, which nots the broken flag on the machine.

**Comment by gozulio** [comment]
So as a temporary fix you can possibly ask an admin to call set_broken proc on a broken console, which might fix it.

**Comment by gozulio** [comment]
The possible fixes for the consoles are:
to either recede the emp_act() proc to not to anything. (easy)
or figure out how to deconstruct the consoles and reconstruct them (maybe not as easy, as i don't think you can deconstruct the R-UST Consoles.)

**Comment by Repede** [comment]
Other fix would be to modernize it, make it work like any other regular computers who relies on circuit boards and all that. (Painful)

**Comment by gozulio** [comment]
Right, Consoles cant be deconstructed because they likely can't fall back through to the original parent proc.
https://github.com/Repede/YawnWiderStation/blob/f2f35697fbdb6eb7c56ac7f91748002f985b6e1f/code/modules/power/fusion/core/core_control.dm#L12-L20

**Comment by Hawk-v3** [comment]
This issue is assigned to @gozulio  :+1:

**Comment by gozulio** [comment]
Fixed in #151
