### ISSUE TITLE
Add german uniforms from previous code

### ISSUE THREAD

**Issue by Repede** [Repede/YawnWiderStation#16]
#### Brief description of the issue
We would like to have the german uniforms from the previous code.
The codebase the uniforms are in is https://github.com/SpadesNeil/VOREstation

**Comment by izac112** [comment]
Here are the icon files not on mob or anything

![stalhelm](https://cloud.githubusercontent.com/assets/12752822/21536452/b9f94294-cd83-11e6-8055-0fe2e1f6f6a3.png)
![waffenrock](https://cloud.githubusercontent.com/assets/12752822/21536453/b9fe68aa-cd83-11e6-9b43-60c028c349c6.png)
![waffenrock_officer](https://cloud.githubusercontent.com/assets/12752822/21536454/ba03a2ac-cd83-11e6-993a-a4d5398c12a4.png)
![einheitsfeldmutze](https://cloud.githubusercontent.com/assets/12752822/21536455/ba04e19e-cd83-11e6-95c7-54ac97dab028.png)
![feldanzug](https://cloud.githubusercontent.com/assets/12752822/21536456/ba07cbf2-cd83-11e6-942c-ed1f9a518993.png)
![feldanzug_officer](https://cloud.githubusercontent.com/assets/12752822/21536457/ba0a3824-cd83-11e6-9932-da81671f0bc4.png)
![feldmutze](https://cloud.githubusercontent.com/assets/12752822/21536458/ba1cf3ce-cd83-11e6-97ca-8a673576de29.png)

**Comment by Repede** [comment]
apparently the worn ones are in the default mob uniform / etc files.

**Comment by izac112** [comment]
The mob sprites and icon sprites are now located in **icons/vore/nazirus_yw.dmi**
and was going to add the code to  **code/modules/vore/fluffstuff/nazirus_yw.dm** but cant seem to get it to work properly
https://github.com/Repede/YawnWiderStation/pull/17

**Comment by izac112** [comment]
This shit is done brah
