### ISSUE TITLE
AIs controlled drones and radio channels

### ISSUE THREAD

**Issue by DeepIndigo** [Repede/YawnWiderStation#171]
#### What you expected to happen
To have channel access during drone operation due to being AI

#### What actually happened
Radio panel on the drone shows the channels as being toggleable and set to "on", but they can not be spoken on, toggled, or received.

#### Steps to reproduce
- 1. Play as AI
- 2. ASSUME DIRECT CONTROL of a drone
- 3. Lose access to all radio channels save for common and binary until RELEASING CONTROL of drone.

#### Code Revision
- Server revision:  - 2018-07-03
be815959c410dbf7d06021be9984d3e24d570b7b 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Hawk-v3** [comment]
I believe, though I am not sure, that this was intentional on the part of upstream to have a downside to the drone form.

**Comment by DeepIndigo** [comment]
why leave the radio showing the channels then? Also that's really less of a downside and more of a "make the AI be bad at their job on a mechanical level", imho. The drone already has the trade-off of being super fragile and prone to zipping past railing.
