### ISSUE TITLE
Silicons and their chatlogs

### ISSUE THREAD

**Issue by DeepIndigo** [Repede/YawnWiderStation#172]
#### What you expected to happen
AIs, borgs, generally anything with an MMI, positronic brain, or robocard to have timestamps on chat like drones do.

#### What actually happened
Only drones have them.

#### Steps to reproduce
- 1. Be a drone (or pilot one as AI) and see chat has timestamps
- 2. Be a borg (or release drone control as AI) and see no time stamps

#### Code Revision
- Server revision:  - 2018-07-03
be815959c410dbf7d06021be9984d3e24d570b7b 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Hawk-v3** [comment]
This is technically a behaviour enhancement, but I can see the reasoning for it.

**Comment by Dwaggy** [comment]
Actually borgs used to have this as default, i remember that as much..so..either it got pulled out or broke if thats the case. not played as a borg for a fair while though myself
