### ISSUE TITLE
Computer3 is bad. and should feel bad. Lets see if we can bring baycode computers.

### ISSUE THREAD

**Issue by Dwaggy** [Repede/YawnWiderStation#173]
As the title says, Computer3 (the interface used for laptops and computers) is..pretty bad, old, and can, especially on the laptops, be incredibly buggy. (lost id's anyone?)
This system has been abandoned by Baycode for some time, and AFAIK, hasnt been updated in some time by either polaris OR vorecode. and is just..slowly declining in to a buggy mess.

While i feel it would be..quite the task, I've been asked to put this up anyway:
Lets see if we can bring in the code for the computer systems that Baycode has.

They however change almost every computer terminal, which is why i believe it will be an effort.

BUT, they change almost every computer and laptop in to a highly modular system, having only one computer instead of many different types, and you can just download the 'program/function' your wanting (assuming your ID has access to it.) , allowing medical staff to check on crew monitors, and engineers to check power systems all on one computer, and so on.

**Comment by Hawk-v3** [comment]
I'd be willing to give this a try. Especially if Polaris want it, so my work helps as many people as possible. Unless they're already porting it!

**Comment by Hawk-v3** [comment]
Stalled due to possibly/probably needing heavy changes upstream. We'll see if it can be done.
