### ISSUE TITLE
Air alarms reporting fire alarms when there is none.

### ISSUE THREAD

**Issue by gozulio** [Repede/YawnWiderStation#174]
#### Brief description of the issue
If you examine some air alarms they will stay "fire alarm in area" when the fire alarm isn't active. Pulling and resetting the fire alarm does not resolve this issue.

#### Steps to reproduce
- Find a room with an air alarm and a fire alarm, with the air alarm stating there is an active fire alarm in the area when there clearly isn't. How alarms get to be like this is unknown.
- Go to the areas fire alarm and pull it, then reset it a second later.
- Return to the air alarm, the alarm should state there is still a fire alarm.

#### Code Revision
- 2018-07-03 be815959c410dbf7d06021be9984d3e24d570b7b 
 
#### Anything else you may wish to add:
- This issue appears to be present in the abandoned restaurant, and the excursion shuttle bay.

**Comment by Hawk-v3** [comment]
Is it only specific alarms/areas?
