### ISSUE TITLE
Respawn timer is 5 minutes, Used to be 1 minute

### ISSUE THREAD

**Issue by Dwaggy** [Repede/YawnWiderStation#181]
Not sure is intentional or not, but as of one of the semi-recent updates, our respawn timer got bumped from one minute to 5. I have not been told this was an official change, so.. I'm putting it up here as a bug report unless another admin says it was intentional.

**Comment by izac112** [comment]
Ace Said he did not think it was intentional But he agreed with me when i said i kinda like it because 

> it Stops people from instantly rejoining
But he also said we could discuss if we should keep it or not which i agree with

**Comment by Dwaggy** [comment]
True! just i wasnt part of that conversation, so assumed it an error. fair enough c:

**Comment by Hawk-v3** [comment]
IT's worth changing the text that pops up saying it'll be a minute before you're allowed to respawn then.
