### ISSUE TITLE
Non-"end Tram" exits eat nifs!

### ISSUE THREAD

**Issue by DeepIndigo** [Repede/YawnWiderStation#188]
#### What you expected to happen
To keep a nif once having it if alive at the time of leaving.

#### What actually happened
NIFs get removed using any exit, 

#### Steps to reproduce
- 1. Have nif
- 2. Exit via cryo, tram door, shortrange teleporter, or an elevator
- 3. Lose your nif as a result

#### Code Revision
- Server revision:  - 2018-07-22
2e3c41cc44147c7fb68410cf257c2b4f8def9a94 
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by izac112** [comment]
This rep has been moved but i link your issues there for future bug reports please make them on https://github.com/Yawn-Wider/YWPolarisVore/issues
