### ISSUE TITLE
Forest colony mapping

### ISSUE THREAD

**Issue by Repede** [Repede/YawnWiderStation#20]
#### Brief description of the issue
New forest colony map

#### Anything else you may wish to add:
Check project.

**Comment by Hawk-v3** [comment]
This still ongoing, or has it been replaced with the other project?

**Comment by Repede** [comment]
Forest colony mapping is the new map that @RadiantFlash7 is working on! If they need coding stuff I figure they can put it here.

**Comment by Hawk-v3** [comment]
Ah, ok. Thanks.
