### ISSUE TITLE
More dogborgs

### ISSUE THREAD

**Issue by Repede** [Repede/YawnWiderStation#21]
#### Brief description of the issue
Doggoborgos only have Security and Medical variant. More should be made!

#### What is needed
- [x] Janihound

- [x] Engihound

- [x] Sciencyhound

- [ ] Servicehound

**Comment by MASMC** [comment]
I'll be working on Scihound. o3o

**Comment by MASMC** [comment]
Sorry for lack of dog borgo from me, I kinda left most places for FTL, but I'll get to working when I have free time if it is still needed?

**Comment by Repede** [comment]
It's no obligations lol

**Comment by Hawk-v3** [comment]
I think there's no servicehound, but the rest came down from upstream.

**Comment by Repede** [comment]
Yup!
