### ISSUE TITLE
Atmos Techs spawn with 2 T-Rays

### ISSUE THREAD

**Issue by MASMC** [Repede/YawnWiderStation#77]
#### Brief description of the issue
See title

#### What you expected to happen
Not having two T-Ray scanners

#### What actually happened
There's a T-Ray scanner in the belt, and one in the pocket.

#### Steps to reproduce
- (Step 1)
- (Step 2)
- (and so on)

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by Hawk-v3** [comment]
#137  Done and done again! Sorry it took so long.
